update scheme format
ReachFive/identity-android-sdk pull request #108
Opened 2020-10-29 15:38 UTC by SelimGribaa

fix Redirection scheme Android SDK and update regex of WebViewClient

2020-10-30 08:54 UTC, roxanemace commented on app/src/main/AndroidManifest.xml
> +                    android:pathPrefix="/LSCdhBOtrPeh8RFLz6bb"
Can we create a resource variable for the client ID in the `settings.xml` file?

2020-10-30 08:55 UTC, roxanemace commented
The `README.md` must be updated :)

2020-10-30 13:52 UTC, roxanemace approved these changes

2020-10-30 13:52 UTC, roxanemace commented on README.md
> +
Saut à la ligne inutile

2020-10-30 16:16 UTC, StanWarz requested changes
Request about the scheme pattern.

2020-10-30 16:16 UTC, StanWarz commented on app/src/main/res/values/settings.xml
> +    <string name="reachfive_client_id">/LSCdhBOtrPeh8RFLz6bb</string>
This / should not belong here.

2020-10-30 16:16 UTC, StanWarz commented on sdk-webview/src/main/java/com/reach5/identity/sdk/webview/ReachFiveLoginActivity.kt
> +        // regex : (reachfive://callback/word character: [a-zA-Z_0-9])(any character zero or more times)
I think the comment `// regex : reachfive://callback/word` is clear enough =)

2020-11-02 09:55 UTC, StanWarz approved these changes

2020-11-02 10:01 UTC, merged